---
- name: coping file and backuping
  hosts: prd
  become: yes
  tasks:
    - name: coping and backuping
      copy:
        src: /tmp/file.txt
        dest: /tmp/
        backup: yes
    - name: making dir and changing permissing
      file:
        path: /tmp/mera_naam
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: u=w,g=r,o=wr

    - name: removing file
      file:
        path: /tmp/file.txt
        state: absent

  
