---
- name: check condition
  hosts: prd
  become: yes
  gather_facts: yes
  tasks:
    - name: removing apache2
      apt:
        name: apache2
        state: absent

      when: ansible_os_family == "Debian"

    - name: removing from redhat
      yum:
        name: httpd
        state: absent

      when: ansible_os_family == "RedHat"
    

