---
- name: downloading files
  become: yes
  hosts: prd
  vars:
    urls: " https://images.pexels.com/photos/19975990/pexels-photo-19975990.jpeg?cs=srgb&dl=pexels-bayfilm9-19975990.jpg&fm=jpg&_gl=1*10vhd30*_ga*MTEzNjk3NzE4NS4xNzYyNjEwNDA5*_ga_8JE65Q40S6*czE3NjI2MTA0MDgkbzEkZzAkdDE3NjI2MTA0MDgkajYwJGwwJGgw " 

    tasks:
      -name: downloading from internet
      get_url:
        url: {{ urls }}
        dest: /tmp/ 
