---
- name: Enable and configure UFW firewall
  hosts: prd
  become: yes

  tasks:
    - name: Enable ufw firewall
      ufw:
        state: enabled

    - name: Allow port 8080/tcp
      ufw:
        rule: allow
        port: 8080
        proto: tcp

    - name: Reload ufw to apply changes
      command: ufw reload

