---
- name: handlers making
  become: yes
  hosts: prd

  tasks:
    - name: disabling firewall port 8080
      ufw:
        port: 80
        proto: tcp
        state: disabled
      notify:
        - reload firewall

  handlers:
    - name: reload firewall
      service:
        name: ufw
        state: restart

