- name: Inginx Install
  hosts: prd
  become: yes
  tasks:
    - name: Install inginx
      apt:
        name: nginx
        state: latest

    - name: staring and enabling
      service:
        name: nginx
        state: started
        enabled: yes

    - name: allowning port 8080
      command: ufw allow 8080
