---
- name: installing and deleteding service
  become: yes
  hosts: prd
  tasks:
    - name: installing nginx 
      apt:
        name: nginx
        state: present

    - name: enabling and running
      service:
        name: nginx
        state: started
        enabled: yes



    - name: killing service
      shell: "pgrep nginx | xargs kill"

