---
- name: creats multiple user
  hosts: prd
  become: yes
  tasks:
    - name: create multi users
      user:
        name: "{{ item }}"
        group: ubuntu
        shell: /bin/bash

      loop:
        - raju
        - shyam
        - babu

