- name: Install Net toll and get ip
  hosts: servers
  become: yes
  tasks:
    - name: Installing net-tool
      apt:
        name: net-tools
        state: latest

    - name: checking_ips
      shell: ifconfig -a | grep -i -n2 enp0s8
