---
- name: script scheduling and running
  hosts: prd
  become: yes
  tasks:
    - name: scheduling script via cron
      cron:
        name: run script
        minute: 1
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        user: root
        job: /tmp/script.sh

    - name: removing cronjob
      cron:
        name: run script
        job: /tmp/script.sh
        disabled: yes
