---
- name: setting env variables
  hosts: prd
  tasks:
    - name: setting env variable
      cron:
        name: PATH
        env: yes
        user: ubuntu
        job: /tmp/test.sh

    - name: setting variable after or befor created variable
      cron:
        name: VAR
        env: yes
        user: ubuntu
        job: /tmp/test.sh
        insertafter: PATH

