---
- name: setting passwords for user in incripted form
  hosts: prd
  become: yes
  tasks:
    #- name: installing pass lib for pass incription
      #apt:
        #name: python3-passlib
          # state: present
      #when: ansible_os_family == "Debian"

    - name: setting password
      user:
        name: nick
        update_password: always
        password: 1234567 

